DROP DATABASE IF EXISTS MentorLink;
CREATE DATABASE MentorLink;
USE MentorLink;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Rating;
DROP TABLE IF EXISTS Goal;
DROP TABLE IF EXISTS Session;
DROP TABLE IF EXISTS Mentorship_Member;
DROP TABLE IF EXISTS User_Subject;
DROP TABLE IF EXISTS Mentorship;
DROP TABLE IF EXISTS Subject;
DROP TABLE IF EXISTS User;

SET FOREIGN_KEY_CHECKS = 1;